name: Docker Image CI.

on:
  push:
    branches: [ "main" ]


# jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: login to docker 
      # run: sudo docker login -u 
      # ${{secrets.DOCKER_USERNAME}} -p 
      # ${{secrets.DOCKER_PASSWORD}}

  #   - name: Build the Docker image
  #     run: docker build -t kene38/aws-nodejs-app .

  #   - name: List Docker images
  #     run: docker images

  #   - name: Push the docker image
  #     run: docker push kene38/aws-nodejs-app
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t kene38/aws-nodejs-app .

      - name: List Docker images
        run: docker images

      - name: Push the Docker image
        run: docker push kene38/aws-nodejs-app
